// ATLProject1.idl : IDL source for ATLProject1
//

// This file will be processed by the MIDL tool to
// produce the type library (ATLProject1.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(6211ed52-9dd3-450f-88c8-2b9c3a08c34d),
	version(1.0),
]
library ATLProject1Lib
{
	importlib("stdole2.tlb");
};

